### ISSUE TITLE
Relecture

### ISSUE THREAD

**Issue by Julien00859** [entwanne/article_python_plongee_asynchrone#1]
Hello hello, je viens de relire l'ensemble du matériel markdown et j'ai quelques remarques à faire sur certains passage. Trois fois rien mais le sujet me tient à coeur alors je les ai tout de même cité ci-dessous. Très bonne série d'article comme à ton habitude, j'attends la suite avec intérêt.

--

On est d'accord que d'un point de vu externe, les tâches jouées par la boucle événementielle *semblent* s'exécuter simultanément. Malgré tout, je pense que le terme *simultané* est surtout adapté aux modèles basés sur les threads, le multiprocess ou même des machines distinctes travaillant de concert et communiquant en réseau. Selon moi, le terme concurrent est plus adapté lorsqu'on parle de l'exécution des tâches dans la boucle événementielle python.

https://github.com/entwanne/article_python_plongee_asynchrone/blame/master/src/1-coroutines.md#L96 Simultané => Concurrente

--

J'aime beaucoup l'exemple qui montre comment croiser des coroutines. Pour améliorer un chouia la qualité du code et se concentrer sur l'essentiel, je placerais les appels `wait_job` et `count_up_to` sur des lignes dédiés. Dans l'état actuel du code, les deux appels sont cachés derrière du code boilerplate (`run_until_complete` et `gather`) ce qui complexifie la relecture de la ligne.

De plus, afficher que le retour de `run_until_complete` est `[None, None]` est également du bruit, je le retirerais.

https://github.com/entwanne/article_python_plongee_asynchrone/blame/master/src/2-awaitable.md#L84 isoler `wait_job` et `count_up_to`

--

C'est du chipo mais je ne peux pas m'empêcher de le soulever. `list.pop(0)` c'est du O(n) qui peut être facilement réglé si on utilise `collections.deque.popleft`.

https://github.com/entwanne/article_python_plongee_asynchrone/blame/master/src/3-event-loop.md#L43

**Comment by entwanne** [comment]
Salut,

Merci tout d'abord pour la lecture et le retour, j'étais surpris de voir une notification.
Pour information il s'agit encore d'un gros brouillon où j'insère les idées comme elles me viennent, toute sa structure peut être amenée à changer (pour équilibrer les parties).
L'article ne sera d'ailleurs pas pour tout de suite, mais son ébauche me servira de support pour une conférence à la PyConFr à la toussaint.

Je fais attention sur l'utilisation du terme « simultané » pour ne pas introduire une idée de parallélisme, mais je veux quand même pouvoir utiliser un mot plus abordable que « concurrent ».
Je souhaite que l'on pusse facilement comprendre qu'une tâche peut être démarrée avant qu'une autre soit terminée et qu'elles s'exécutent ainsi « en même temps ».

Je vais voir pour rendre l'exemple en question plus clair, j'ai de toute manière des contraintes strictes sur la longueur des lignes lorsque je veux générer les slides PDF.
Pour le retour, je le trouve peu utile mais il se trouve qu'il est présent dans la console quand la ligne est exécutée, je ne veux pas qu'une personne exécutant chez elle puisse trouver cela anormal. Mais une phrase expliquant la présence de cette valeur de retour pourrait aider.

De la même manière, je pense ajouter une note pour préciser que l'utilisation d'une liste n'est pas optimale et qu'une vraie queue est plus appropriée, mais conserver le code ainsi, le plus abordable possible.

Merci encore.
